services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ${APP_NAME:-symfony}_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:rw
      - ./var:/var/www/html/var:rw
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - symfony_network

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: ${APP_NAME:-symfony}_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - symfony_network
  ###< doctrine/doctrine-bundle ###

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER:
    ports:
      - "8082:8080"
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME:-symfony}_nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - symfony_network
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  symfony_network:
    driver: bridge
